name: demo_plugin_platform_interface
description: A common platform interface for the demo_plugin plugin.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0-242.0.dev
  flutter: '>=3.40.0-1.0.pre-162'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
